name: Fetch Daily Image

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日UTC0時（日本時間9時）
  workflow_dispatch:  # 手動実行も可能

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch image
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python scripts/fetch_images.py

      - name: Commit & push
        run: |
          git config user.name "SMZPP"
          git config user.email "lipeng0105@gmail.com"
          git add images/
          git commit -m "Add daily image $(date +'%Y-%m-%d')" || echo "No changes"
          git push
